### ISSUE TITLE
Any functions planned for getting the albums?

### ISSUE THREAD

**Issue by PierLucaLanzi** [jameswenzel/pylyrics3#3]
Hi! Thanks a lot it works great. I was desperate as PyLyrics does not work anymore.

Are you planning to have a function to get the list of albums and the songs for each album?

Thank you again!

**Comment by sashaperigo** [comment]
Great idea @PierLucaLanzi! I'll try to look into this this week.

**Comment by emo-eth** [comment]
Sorry for not initially responding, thanks @sashaperigo.
I think this is a good idea but has the potential to break backwards compatibility so design is important - as of right now I'm thinking it'd be best to add optional flags to the `get_artist_lyrics` function to specify whether or not to break the result into albums.
Then there comes the question of whether it should return a nested `dict` or a `list` of `dicts` representing each album - each has value, so I think it could be its own flag.
We could add optional flags `albums=False` and `nested=True`.
Parsing out albums from an artist page should be straightforward, but adding a new function `get_album_lyrics(artist, album)` might be more hit-or-miss depending on what the search results return.

**Comment by emo-eth** [comment]
Implemented in 1e063e66425fa279f22cbb7a4055d19f4152be20 with version `1.0.0`
