### ISSUE TITLE
Can't install package in python 3.6

### ISSUE THREAD

**Issue by jding99** [jameswenzel/pylyrics3#4]
I'm trying to pip install pylyrics3 but I keep getting a "ModuleNotFoundError: No module named 'version'
Command "python setup.py egg_info" failed with error code 1" 
error

**Comment by emo-eth** [comment]
Do you happen to be using a Windows or Linux machine? I think I know what the problem was. I pushed a change 1cff8afa756f57bdb8698438e68f7b9bd803f012, it should work now. Let me know.

**Comment by jding99** [comment]
I'm using a Mac; unfortunately still not working

**Comment by darkzbaron** [comment]
same here

**Comment by emo-eth** [comment]
@jding99 @darkzbaron I have a couple more machines set up so I'll look into it now. In the meantime, you can download the repo and install by running `python setup.py install` in a terminal in the directory.

**Comment by emo-eth** [comment]
@jding99 @darkzbaron Seems to be fixed now, was able to install on a debian distro. Give it a shot and let me know if it works. You may have to use the `--no-cache-dir` flag so `pip` fetches the latest version.

**Comment by darkzbaron** [comment]
all good, thanks dev ;)
