### ISSUE TITLE
Artist names should not have to be lowercase

### ISSUE THREAD

**Issue by hanmertens** [jameswenzel/pylyrics3#6]
I tried to run the following code with version 1.0.4:

    >>> import pylyrics3
    >>> pylyrics3.get_artist_lyrics('Adele')

It prints the name "Adele" an awful lot, but the returned dictionary is empty. It works fine if I use `adele` in lowercase, so I expect a `.lower()` or the like is missing somewhere in the code. In any case, all the printing seems a bit unnecessary unless you're debugging.

**Comment by emo-eth** [comment]
Good catch on both fronts, indeed leftover from debugging. Also caught a different bug involving capitalization in constructed URLs. Fix is live in v1.0.5, give it an `--upgrade` and let me know if you run into other issues.
